spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password: root
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia
    default-property-inclusion: non_null


mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
config:
  jwt:
    expire: 3600
    secret: hICStkIMhe8tZ5QSIBPf50wJNQXRm1ayZjuQUYKE2U0vlpm1HhaTr2Bx0NDlk1t5Dy0g52JUGkLX4wtf1nFHPq
    header: Authorization
